import Head from 'next/head'
import Image from 'next/image'
import SideBar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="mx-auto max-h-screen overflow-hidden lg:max-w-6xl">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main className='grid grid-cols-9'>
       <SideBar />

       <Feed />
       
       <Widgets />
      </main>
    </div>
  )
}
