import Head from 'next/head'
import Image from 'next/image'
import SideBar from '../components/Sidebar'
import Feed from '../components/Feed'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main>
       <SideBar />
       <Feed />
      </main>
    </div>
  )
}
